### ISSUE TITLE
feature: Load local file

### ISSUE THREAD

**Issue by woile** [elmasse/postcasts-mvp#10]
@elmasse do you think loading a local file would be possible?

Thanks!

**Comment by elmasse** [comment]
Yup! Totally. I'll give it a try.

**Comment by elmasse** [comment]
This should be already deployed and ready to be tested.

🚀

**Comment by woile** [comment]
Amazing, thanks @elmasse 
Is there a button or something? I don't see any.

**Comment by elmasse** [comment]
At bottom of the home page the form has a `Load` button: 

<img width="624" alt="pc-home" src="https://user-images.githubusercontent.com/223235/35044450-2b46666a-fb6f-11e7-9a75-5a52226c0006.png">

Same under `/play` route

<img width="541" alt="pc-play" src="https://user-images.githubusercontent.com/223235/35044452-2e58b3c6-fb6f-11e7-8f53-081048d7e74f.png">

Maybe I need to improve the wording in the form a bit.

**Comment by woile** [comment]
Nono, it's okay the wording I guees. I was seeing the old screen. 

![image](https://user-images.githubusercontent.com/2585816/35044836-1abe8674-fb92-11e7-9e62-d179a4bb82bd.png)

If I try in incognito mode it works perfect. 

Thanks
